# Assignmnet 360_fruits Data
# Ahmad Ali
# C1-04


In [1]:
import cv2
import os # use to read folders and inside files
folder_path=[
    r'C:\Users\Ahmad Ali\Desktop\data\fruits-360-original-size\fruits-360-original-size\Training\apple_6',
    r'C:\Users\Ahmad Ali\Desktop\data\fruits-360-original-size\fruits-360-original-size\Training\apple_braeburn_1'
]

In [2]:
dataset=[]

for name in folder_path: # range=no.of Folders (3)
    folder_name=os.path.basename(name)   # get the name of folder's only
    print(folder_name)
    
    for file in os.listdir(name): # range=no.of Files in folder so total iterations(total files in each folder)
        image_path=os.path.join(name,file)
    
# Merge the [folder_path+image_file_name]     

        if os.path.isfile(image_path):
            image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
            if image is not None:
                resized_image = cv2.resize(image, (250,250))
                flattened_image = resized_image.flatten().tolist()
                dataset.append(flattened_image + [folder_name])


apple_6
apple_braeburn_1
apple_crimson_snow_1


In [4]:
import pandas as pd
df=pd.DataFrame(dataset, columns=[f'pixel_{i+1}' for i in range(250*250)] +['label'])
df.to_csv('Image_data.csv',index=False)

In [4]:
X=df.drop('label',axis=1)
X=X/255
y=df['label']

# SVC

In [13]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,confusion_matrix
import time

lab=LabelEncoder()
y1=lab.fit_transform(y)

X_train,X_test,y_train,y_test=train_test_split(X,y1,test_size=0.2,random_state=42)

st=time.process_time()

model=SVC(kernel='linear',C=1)

model.fit(X_train,y_train)

y_pred=model.predict(X_test)

acc1=accuracy_score(y_test,y_pred)
print('Accuracy of SVC= ',acc1)

con=confusion_matrix(y_test,y_pred)
print('Confusion Matrix = \n',con)

end=time.process_time()

tt=end-st
print('CPU Process time',tt,'sec')


Accuracy of SVC=  1.0
Confusion Matrix = 
 [[60  0  0]
 [ 0 65  0]
 [ 0  0 66]]
CPU Process time 12.5 sec


# Logistic Regression

In [7]:
import time
st=time.process_time() # CPU process time calculation
from sklearn.linear_model import LogisticRegression
model1=LogisticRegression(max_iter=200)

model1.fit(X_train,y_train)

y_pred=model1.predict(X_test)

acc2=accuracy_score(y_test,y_pred)
print('Accuracy of Logistic Regression= ',acc2)

con=confusion_matrix(y_test,y_pred)
print('Confusion Matrix = \n',con)
end=time.process_time()

tt1=end-st
print('CPU Process time',tt1,'sec')

Accuracy of Logistic Regression=  1.0
Confusion Matrix = 
 [[60  0  0]
 [ 0 65  0]
 [ 0  0 66]]
CPU Process time 71.875 sec


# Decision Tree Classifier

In [8]:
import time
st=time.process_time() # CPU process time calculation

# CPU time is how many seconds the CPU was busy.

from sklearn.tree import DecisionTreeClassifier
model1=DecisionTreeClassifier()

model1.fit(X_train,y_train)

y_pred=model1.predict(X_test)

acc3=accuracy_score(y_test,y_pred)
print('Accuracy of Decision Tree Classifier= ',acc3)

con=confusion_matrix(y_test,y_pred)
print('Confusion Matrix = \n',con)
end=time.process_time()

tt2=end-st
print('CPU Process time',tt2,'sec')

Accuracy of Decision Tree Classifier=  1.0
Confusion Matrix = 
 [[60  0  0]
 [ 0 65  0]
 [ 0  0 66]]
CPU Process time 13.75 sec


# Random Forest Classifier

In [9]:
import time
st=time.process_time() # CPU process time calculation

# CPU time is how many seconds the CPU was busy.

from sklearn.ensemble import RandomForestClassifier
model1=RandomForestClassifier()

model1.fit(X_train,y_train)

y_pred=model1.predict(X_test)

acc4=accuracy_score(y_test,y_pred)
print('Accuracy of Random Forest Classifier= ',acc4)

con=confusion_matrix(y_test,y_pred)
print('Confusion Matrix = \n',con)
end=time.process_time()

tt3=end-st
print('CPU Process time',tt3,'sec')

Accuracy of Random Forest Classifier=  1.0
Confusion Matrix = 
 [[60  0  0]
 [ 0 65  0]
 [ 0  0 66]]
CPU Process time 6.3125 sec


# K Neighbors Classifier

In [10]:
import time
st=time.process_time() # CPU process time calculation

import numpy as np
X_train = np.ascontiguousarray(X_train)
X_test = np.ascontiguousarray(X_test)

# CPU time is how many seconds the CPU was busy.

from sklearn.neighbors import KNeighborsClassifier
model1=KNeighborsClassifier()

model1.fit(X_train,y_train)

y_pred=model1.predict(X_test)

acc5=accuracy_score(y_test,y_pred)
print('Accuracy of K Neighbors Classifier= ',acc5)

con=confusion_matrix(y_test,y_pred)
print('Confusion Matrix = \n',con)
end=time.process_time()

tt4=end-st
print('CPU Process time',tt4,'sec')

Accuracy of K Neighbors Classifier=  1.0
Confusion Matrix = 
 [[60  0  0]
 [ 0 65  0]
 [ 0  0 66]]
CPU Process time 3.921875 sec


In [16]:
a=pd.DataFrame({
    'SVC_ACC':acc1,
    'SVC_CPU_PT(sec)':tt,
    'Logistic_ACC':acc2,
    'Logistic_CPU_PT(sec)':tt1,
    'DTC_ACC':acc3,
    'DTC_CPU_PT(sec)':tt2,
    'RFC_ACC':acc4,
    'RFC_CPU_PT(sec)':tt3,
    'KNC':acc5,
    'KNN_CPU_PT(sec)':tt4,
    'Best wrt time(sec)':'KNN'
},index=[0])
a

SVC_ACC  SVC_CPU_PT(sec)  Logistic_ACC  Logistic_CPU_PT(sec)  DTC_ACC  \
0      1.0             12.5           1.0                71.875      1.0   

   DTC_CPU_PT(sec)  RFC_ACC  RFC_CPU_PT(sec)  KNC  KNN_CPU_PT(sec)  \
0            13.75      1.0           6.3125  1.0         3.921875   

  Best wrt time(sec)  
0                KNN

## AttributeError: 'Flags' object has no attribute 'c_contiguous'
## Explaination:-
The error occurs in the scikit-learn library while trying to compute distances between data points for the k-nearest neighbors (KNN) algorithm. In the KNN algorithm, distances between data points are calculated to find the k-nearest neighbors for each data point.

The problem lies in how the input data is organized in memory. In Python, data can be stored in different memory layouts. Two common layouts are C-contiguous (row-major order) and Fortran-contiguous (column-major order). The distinction between these two memory layouts is important when performing certain operations on data, such as calculating distances between points.

## C-contiguous (row-major order):-

In the context of scikit-learn's KNN algorithm, the input data is expected to be in a C-contiguous memory layout. The C-contiguous layout means that the elements of each row in a 2D array are stored in adjacent memory locations, making it efficient to access consecutive elements in a row. This layout is suitable for most NumPy operations and many algorithms in scikit-learn.

## Fortran-contiguous (column-major order):-

On the other hand, Fortran-contiguous layout means that the elements of each column in a 2D array are stored in adjacent memory locations, making it efficient to access consecutive elements in a column.

The error you encountered arises because scikit-learn's KNN algorithm requires C-contiguous memory layout for the input data. The c_contiguous attribute is used to check if the input data is in the required layout. If the input data is not C-contiguous, scikit-learn tries to use other available algorithms for computing distances that work with non-C-contiguous data. However, in some cases, these alternatives might not be available, leading to the AttributeError you encountered.

To resolve the issue, you explicitly converted your input data to C-contiguous memory layout using np.ascontiguousarray, which ensures that the data is in the correct format for the KNN algorithm to work without any issues.

In summary, the issue was caused by the memory layout of the input data not being C-contiguous, which is a requirement for scikit-learn's KNN algorithm. By converting the data to C-contiguous layout, the problem was resolved, and the algorithm could successfully compute distances and make predictions.

# Solution
X_train = np.ascontiguousarray(X_train)
X_test = np.ascontiguousarray(X_test)