# Assignment01-C1-04-6-06-2023
# Ahmad Ali

# Task 1

In [10]:
import numpy as np
a=np.arange(10).reshape(2,-1)
# print(a)
b=np.repeat(1,10).reshape(2,-1)
# print(b)
arr=np.vstack((a,b))
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


# Task 2

In [24]:
a=np.array([1,2,3])
b,c,d=np.repeat(a[0],3),np.repeat(a[1],3),np.repeat(a[2],3)
e=np.array([b,c,d,a,a]).reshape(-1)
e

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3])

# Task 3

In [99]:
a=np.array([5,7,9,8,6,4,5])
b=np.array([6,3,4,8,9,7,1])
def pair_max(a,b):
     return np.max((a,b),axis=0)
pair_max(a,b)

array([6, 7, 9, 8, 9, 7, 5])

# Task 4

In [37]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
a[[1,2]]=a[[2,1]]
print('swap array')
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
swap array
[[1 2 3]
 [7 8 9]
 [4 5 6]]


# Task 5

In [85]:
a=np.array([1,2,3,4,5])
b=np.array([5,6,7,8,9])
a=np.delete(a,np.where(a==np.intersect1d(a,b)))
a


array([1, 2, 3, 4])