# Assignment 19-7-2023
# Ahmad Ali
# C1-04

# Uploading Image

In [35]:
import cv2
i=cv2.imread('the-black-apple.jpg',cv2.IMREAD_GRAYSCALE)
cv2.imshow('Apple',i)
cv2.waitKey(500)
cv2.destroyAllWindows()

# Color Intesity changing

In [114]:
import cv2
image=cv2.imread('image1.jpg')
cv2.imshow('Friend',image)
cv2.waitKey(0)
cv2.destroyAllWindows()


image_gray=cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
# image_gray=cv2.cvtColor(image,cv2.COLOR_BGR2RGB)

cv2.imshow('gray_fig',image_gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

image1=cv2.cvtColor(image_gray, cv2.COLOR_GRAY2BGR)

cv2.imshow('color_image',image1)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [113]:
import numpy as np

i=cv2.imread('the-black-apple.jpg',cv2.IMREAD_GRAYSCALE)
image1=cv2.equalizeHist(i)

image=np.hstack((i,image1))
cv2.imshow('image',image)
cv2.waitKey(500)
cv2.destroyAllWindows()

image2=cv2.normalize(image,None,0,255,cv2.NORM_MINMAX,cv2.CV_8U)
cv2.imshow('image',image2)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Often image normalization is used to increase contrast which aids in improved feature extraction or image segmentation. Often times Image Normalization is used to remove noise from the picture.

# Channel Manipulation

In [111]:
image=cv2.imread('image6.jpg')
r,g,b=cv2.split(image)
cv2.imshow('blue_image',r)
cv2.imshow('green_image',g)
cv2.imshow('red_image',b)
cv2.waitKey(500)
cv2.destroyAllWindows()

# Channel Create 3 images with r,g,b colors

# Merging Channel's

In [112]:
merging=cv2.merge((r,g,b))
cv2.imshow('merge_image',merging)
cv2.waitKey(500)
cv2.destroyAllWindows()

# Arithmatic Operations

## Addition

In [69]:
i1=cv2.imread('image5.jpg')
i2=cv2.imread('image6.jpg')
i1=np.resize(i1,i2.shape)
add_image=cv2.add(i1,i2)
cv2.imshow('add_image',add_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Subtraction

In [80]:
i1=cv2.imread('image5.jpg')
i2=cv2.imread('image6.jpg')
i1=np.resize(i1,i2.shape)
subtract_image=cv2.subtract(i1,i2)
add_image=cv2.add(i1,i2)
cv2.imshow('add_image',add_image)
cv2.imshow('subtract_image',subtract_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Filter

In [109]:
i3=cv2.imread('image8.jpg')
image=cv2.blur(i3,(20,20))
cv2.imshow('filter_image',image)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Logical Operators

# Bitwise_not Operators

In [108]:
i3=cv2.imread('image8.jpg')
i4=cv2.bitwise_not(i3)
cv2.imshow('filter_image',i4)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Bitwise_and Operators

In [107]:
i3=cv2.imread('image9.jpg')
i4=cv2.imread('image10.jpg')
i4=np.resize(i4,i3.shape)
image=cv2.bitwise_and(i3,i4,mask = None)
cv2.imshow('filter_image',image)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Bitwise_or Operators

In [127]:
i3=cv2.imread('image9.jpg')
i4=cv2.imread('image10.jpg')
i4=np.resize(i4,i3.shape)
image=cv2.bitwise_or(i3,i4,mask = None)
cv2.imshow('filter_image',image)
cv2.waitKey(0)
cv2.destroyAllWindows()

array_i3=i3[:,:]
print(array_i3)
print()

array=image[:,:]
array

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]



array([[[124, 101,  85],
        [121,  98,  82],
        [121,  98,  82],
        ...,
        [170, 137, 111],
        [187, 152, 126],
        [193, 156, 130]],

       [[199, 160, 132],
        [205, 169, 139],
        [213, 182, 149],
        ...,
        [159, 119,  94],
        [152, 112,  87],
        [155, 116,  88]],

       [[164, 125,  97],
        [177, 141, 111],
        [203, 164, 136],
        ...,
        [239, 213, 189],
        [226, 198, 174],
        [194, 168, 144]],

       ...,

       [[ 96, 134, 166],
        [ 98, 135, 163],
        [111, 143, 172],
        ...,
        [ 24,  35,  49],
        [ 29,  40,  54],
        [ 30,  43,  57]],

       [[ 33,  48,  64],
        [ 27,  43,  59],
        [ 19,  34,  53],
        ...,
        [121, 161, 189],
        [121, 161, 189],
        [122, 162, 190]],

       [[121, 161, 189],
        [118, 158, 186],
        [112, 152, 180],
        ...,
        [122, 157, 183],
        [119, 156, 182],
        [117, 154, 180]]

# Bitwise_xor Operation

In [121]:
i3=cv2.imread('image9.jpg')
i4=cv2.imread('image10.jpg')
i4=np.resize(i4,i3.shape)
image=cv2.bitwise_xor(i3,i4,mask = None)
cv2.imshow('filter_image',image)
cv2.waitKey(0)
cv2.destroyAllWindows()